[phases.setup]
nixPkgs = ["nodejs_18", "npm"]

[phases.install]
cmds = ["cd frontend || true", "npm install"]

[phases.build]
cmds = ["cd frontend || true", "npm run build"]

[start]
cmd = "cd frontend && npm run preview -- --host"

